# This is a basic workflow to help you get started with Actions

name: Merge to MASTER

# Controls when the workflow will run
on:
   workflow_run:
     workflows: ["Deploy to DEV"]
     types: [completed] #requested

jobs:
   merge-to-master:
     runs-on: ubuntu-latest
     if: ${{ github.event.workflow_run.conclusion == 'success' }}
     steps:
       - name: Merge development -> master
         uses: devmasx/merge-branch@master
         with:
          type: now
          from_branch: develop
          target_branch: master
          github_token: ${{ github.token }}
